### ISSUE TITLE
TODO 16주차 남은 할 일

### ISSUE THREAD

**Issue by shine-jung** [PP3-team-project/spring-team-project#6]
improve @aidanbae0201 
---
- [ ] 파일 업로드 기능 구현
- [ ] 시간 표시 형식 변경

회원 가입 @seokmin01 
---
- [ ] 회원가입 (member 추가) 기능 구현
- [ ] 회원가입 form 디자인
- [ ] 내 정보 보기 페이지

추가 기능
---
- [x] 필터 기능 추가
- [x] 정렬 기능 추가

**Comment by aidanbae0201** [comment]
제가 파일 업로드 기능을 추가하려고 했지만... 저희가 배운 내용을 스프링 쪽으로, 그리고 mybatis 까지 이용해서 하려고 하니 어찌해야 할 줄 모르겠더라구요... 그래서 인터넷에서 찾아서 스프링에서 파일 업로드 하는 법으로 하려고 하는데, 이렇게 하면 db에 연결하는 게 애매해서.. 어찌할 줄 모르겠습니다ㅠㅠ

**Comment by aidanbae0201** [comment]
우선 카테고리 별 정렬 기능을 넣었습니다! 코드 복붙해서 페이지만 여러개 만들면 될 것 같아요!

**Comment by shine-jung** [comment]
> 우선 카테고리 별 정렬 기능을 넣었습니다! 코드 복붙해서 페이지만 여러개 만들면 될 것 같아요!

자바스크립트를 이용하면 페이지를 여러개 만들 필요가 없습니다!
#9 해당 PR을 확인해주세요
확인이 끝나면 Merge 부탁드립니다

**Comment by shine-jung** [comment]
> 제가 파일 업로드 기능을 추가하려고 했지만... 저희가 배운 내용을 스프링 쪽으로, 그리고 mybatis 까지 이용해서 하려고 하니 어찌해야 할 줄 모르겠더라구요... 그래서 인터넷에서 찾아서 스프링에서 파일 업로드 하는 법으로 하려고 하는데, 이렇게 하면 db에 연결하는 게 애매해서.. 어찌할 줄 모르겠습니다ㅠㅠ

회원가입기능하고 파일 업로드 기능은 이번에 꼭 구현하지 않아도 될거 같습니다
5개 이상의 input type를 보여줘야해서 파일 선택 tag는 그대로 놔두고
보고서에 추가로 구현하고 싶은 부분에 적는걸로 하는건 어떨까요?

**Comment by aidanbae0201** [comment]
#9 번 확인했습니다!! 네 그렇게 하도록 할게요ㅠㅠ
